export const ENGLISH_LANGUAGE_KEY = 'en';
export const SPANISH_LANGUAGE_KEY = 'es';
export const FRENCH_LANGUAGE_KEY = 'fr';

export const DEFAULT_LANGUAGE_KEY = ENGLISH_LANGUAGE_KEY;

export const ALLOWED_LANGUAGES_LIST = [
  ENGLISH_LANGUAGE_KEY,
  SPANISH_LANGUAGE_KEY,
  FRENCH_LANGUAGE_KEY,
];
